services:
  mongodb:
    image: mongo:8.0.8
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 4703
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./data:/data/db